### ISSUE TITLE
[Bug]: Contract - Resurrection does not remove the shown DCAU cost.

### ISSUE THREAD

**Issue by neothon** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#28]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

#brainiac

### What happened?

Brave / Windows 10

I died and used the ressurect action at the healer's hut. The price for the action should of been 2.2 DCAU but I only paid 0.000000000000000556 DCAU

https://testnet.snowtrace.io/tx/0x51c9bbc449eaa6216e1f67415ec1ba176eb544e53af7ff73fc18233d2963c361

Video to come
https://youtu.be/7Lyu9se2-9g?t=344
5:50 to 6:50 

https://discord.com/channels/887555671963340862/1032917658078814238

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
Yup, was able to reproduce it. Initially I thought that the frontend didn't update the balance in time but that doesn't seem to be the issue

**Comment by Polypup** [comment]
I'll take a look.

**Comment by Polypup** [comment]
This has been fixed. The heal price was being fetched instead of the resurrect price. We also didn't update the resurrect per dollar correctly since 1e18 is being used now for precision. 

The correct prices are now being displayed and being charged correctly

https://github.com/Dragon-Crypto-Gaming/aurum-draconis-prototype/commit/ee8c189e45e41521d279e01011139495ee7f7992
